# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"+\n\rKeyValMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"!\n\x0eSuccessMessage\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nKeyMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"3\n\x11SuccessValMessage\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"_\n\x14RequestTermIdMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"W\n\x05\x45ntry\x12 \n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x11.Entry.EntryEntry\x1a,\n\nEntryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8e\x01\n\x13\x41ppendTermIdMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x17\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x06.Entry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"1\n\x11TermResultMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x08\"\x1f\n\rPeriodMessage\x12\x0e\n\x06period\x18\x01 \x01(\x05\"\x0e\n\x0c\x45mptyMessage\"0\n\rLeaderMessage\x12\x0e\n\x06leader\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2\xaa\x02\n\x07Service\x12\x38\n\x0bRequestVote\x12\x15.RequestTermIdMessage\x1a\x12.TermResultMessage\x12\x39\n\rAppendEntries\x12\x14.AppendTermIdMessage\x1a\x12.TermResultMessage\x12(\n\x07Suspend\x12\x0e.PeriodMessage\x1a\r.EmptyMessage\x12*\n\tGetLeader\x12\r.EmptyMessage\x1a\x0e.LeaderMessage\x12)\n\x06SetVal\x12\x0e.KeyValMessage\x1a\x0f.SuccessMessage\x12)\n\x06GetVal\x12\x0b.KeyMessage\x1a\x12.SuccessValMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENTRY_ENTRYENTRY._options = None
  _ENTRY_ENTRYENTRY._serialized_options = b'8\001'
  _KEYVALMESSAGE._serialized_start=14
  _KEYVALMESSAGE._serialized_end=57
  _SUCCESSMESSAGE._serialized_start=59
  _SUCCESSMESSAGE._serialized_end=92
  _KEYMESSAGE._serialized_start=94
  _KEYMESSAGE._serialized_end=119
  _SUCCESSVALMESSAGE._serialized_start=121
  _SUCCESSVALMESSAGE._serialized_end=172
  _REQUESTTERMIDMESSAGE._serialized_start=174
  _REQUESTTERMIDMESSAGE._serialized_end=269
  _ENTRY._serialized_start=271
  _ENTRY._serialized_end=358
  _ENTRY_ENTRYENTRY._serialized_start=314
  _ENTRY_ENTRYENTRY._serialized_end=358
  _APPENDTERMIDMESSAGE._serialized_start=361
  _APPENDTERMIDMESSAGE._serialized_end=503
  _TERMRESULTMESSAGE._serialized_start=505
  _TERMRESULTMESSAGE._serialized_end=554
  _PERIODMESSAGE._serialized_start=556
  _PERIODMESSAGE._serialized_end=587
  _EMPTYMESSAGE._serialized_start=589
  _EMPTYMESSAGE._serialized_end=603
  _LEADERMESSAGE._serialized_start=605
  _LEADERMESSAGE._serialized_end=653
  _SERVICE._serialized_start=656
  _SERVICE._serialized_end=954
# @@protoc_insertion_point(module_scope)
